## Grad decent

Using fundtion about grad decent(Metrix) finishs a simple example by AutoGrad module:

<center>$$1 * a + b =2 $$
<center>$$3*a + b = 4 $$

$$ X =
\left [\begin{array}{cccc}
1 & 1 \\
3 & 1 \\
\end{array}\right]
$$

$$ y = 
\left[\begin{array}{cccc}
2 \\
4\\
\end{array}\right]
$$

$$\hat w = \left[\begin{array}{cccc}
a\\
b\\
\end{array}\right]
$$

In [1]:
import torch

In [17]:
# setting paramters
weights = torch.zeros(2, 1, requires_grad = True)
weights

tensor([[0.],
        [0.]], requires_grad=True)

In [18]:
X = torch.tensor([[1,1.],[3,1]], requires_grad = True)
X

tensor([[1., 1.],
        [3., 1.]], requires_grad=True)

In [19]:
y = torch.tensor([2,4.], requires_grad = True)
y

tensor([2., 4.], requires_grad=True)

In [20]:
eps = torch.tensor(0.01, requires_grad = True)
eps

tensor(0.0100, requires_grad=True)

In [21]:
grad = torch.mm(X.t(), (torch.mm(X, weights) - y))/2

In [22]:
grad

tensor([[-4., -8.],
        [-2., -4.]], grad_fn=<DivBackward0>)

In [24]:
weights = weights - eps * grad

In [25]:
weights

tensor([[0.0400, 0.0800],
        [0.0200, 0.0400]], grad_fn=<SubBackward0>)

>- liter 3 times

In [26]:
for k in range(3):
    grad = torch.mm(X.t(),(torch.mm(X,weights)-y))/2
    weights = weights - eps * grad

In [27]:
weights

tensor([[0.1462, 0.2923],
        [0.0742, 0.1485]], grad_fn=<SubBackward0>)

In [37]:
def gradDescent(X,y,eps = torch.tensor(0.01,requires_grad=True), numIt = 1000):
    m,n = X.shape
    weights = torch.zeros(n, 1, requires_grad=True)
    for k in range(numIt):
        grad = torch.mm(X.t(),(torch.mm(X,weights)-y))/2
        weights = weights - eps * grad
    return weights

In [38]:
X = torch.tensor([[1.,1],[3, 1]], requires_grad = True)
y = torch.tensor([2.,4], requires_grad = True).reshape(2,1)

In [39]:
gradDescent(X,y)

tensor([[1.0372],
        [0.9102]], grad_fn=<SubBackward0>)

In [40]:
weights = gradDescent(X,y, numIt=10000)
weights

tensor([[1.0000],
        [1.0000]], grad_fn=<SubBackward0>)